import 'package:flutter/material.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedGroup6Widget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedGroup38Widget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedRectangle10Widget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedGeneralInformationWidget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedDownload11Widget4.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedGroup5Widget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedRectangle1Widget4.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedGroup35Widget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedGroup3Widget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedGroup9Widget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedOngoingSemesterWidget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedCourseRegistrationWidget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedGroup10Widget.dart';
import 'package:flutterapp/cse_202100app/generatedhomepagewidget/generated/GeneratedRectangle12Widget.dart';
import 'package:flutterapp/view/func.dart';

/* Frame Home page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepageWidget extends StatefulWidget {
  @override
  State<GeneratedHomepageWidget> createState() =>
      _GeneratedHomepageWidgetState();
}

class _GeneratedHomepageWidgetState extends State<GeneratedHomepageWidget> {
  String? ag;
  String? name;
  String? roll;
  String? parent;
  var isloaded = false;
  @override
  void didChangeDependencies() async {
    await Future.delayed(Duration.zero, () {
      String args = ModalRoute.of(context)!.settings.arguments as String;
      ag = args;
    });
    var uid = UId(ag!);
    uid.fetchVal().then((val) {
      name = val.name;
      roll = val.roll;
      parent = val.parent;
      setState(() {
        isloaded = true;
      });
    });
    super.didChangeDependencies();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // drawer: Drawer(
      //   child: Column(
      //     children: [
      //       SizedBox(
      //         height: 30,
      //       ),
      //       ListTile(
      //           leading: Icon(Icons.admin_panel_settings),
      //           title: Text('Admin'),
      //           onTap: () {
      //             Navigator.of(context).pushNamed('/admin', arguments: parent);
      //           }),
      //     ],
      //   ),
      // ),
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
            onPressed: () {
              Navigator.of(context).pushReplacementNamed('/');
            },
            icon: Icon(
              Icons.logout,
              color: Colors.black,
            )),
        // Builder(builder: (BuildContext context) {
        //   return IconButton(
        //     color: Colors.black,
        //     icon: Icon(Icons.accessible),
        //     onPressed: () => Scaffold.of(context).openDrawer(),
        //   );
        // }),
      ),
      body: isloaded
          ? ClipRRect(
              borderRadius: BorderRadius.zero,
              child: LayoutBuilder(
                  builder: (BuildContext context, BoxConstraints constraints) {
                return SingleChildScrollView(
                  scrollDirection: Axis.vertical,
                  child: Container(
                      height: 1250.0,
                      child: Stack(children: [
                        Container(
                            width: constraints.maxWidth,
                            child: Container(
                              width: 360.0,
                              height: 1250.0,
                              child: Stack(
                                  clipBehavior: Clip.none,
                                  fit: StackFit.expand,
                                  alignment: Alignment.center,
                                  children: [
                                    ClipRRect(
                                      borderRadius: BorderRadius.zero,
                                      child: Container(
                                        color:
                                            Color.fromARGB(255, 255, 255, 255),
                                      ),
                                    ),
                                    Positioned(
                                      left: 0.0,
                                      top: 195.0,
                                      right: null,
                                      bottom: null,
                                      width: 360.0,
                                      height: 1055.0,
                                      child: GeneratedRectangle1Widget4(),
                                    ),
                                    Positioned(
                                      left: 125.0,
                                      top: 39.0,
                                      right: null,
                                      bottom: null,
                                      width: 110.0,
                                      height: 110.0,
                                      child: GeneratedDownload11Widget4(),
                                    ),
                                    Positioned(
                                      left: 34.0,
                                      top: 302.0,
                                      right: null,
                                      bottom: null,
                                      width: 292.0,
                                      height: 197.0,
                                      child:
                                          GeneratedGroup10Widget(name!, roll!),
                                    ),
                                    Positioned(
                                      left: 103.0,
                                      top: 244.0,
                                      right: null,
                                      bottom: null,
                                      width: 156.0,
                                      height: 21.0,
                                      child:
                                          GeneratedGeneralInformationWidget(),
                                    ),
                                    Positioned(
                                      left: 108.0,
                                      top: 626.0,
                                      right: null,
                                      bottom: null,
                                      width: 147.0,
                                      height: 21.0,
                                      child: GeneratedOngoingSemesterWidget(),
                                    ),
                                    Positioned(
                                      left: 54.0,
                                      top: 552.0,
                                      right: null,
                                      bottom: null,
                                      width: 252.0,
                                      height: 42.0,
                                      child: GeneratedGroup3Widget(),
                                    ),
                                    Positioned(
                                      left: 76.0,
                                      top: 677.0,
                                      right: null,
                                      bottom: null,
                                      width: 209.0,
                                      height: 42.0,
                                      child: GeneratedGroup5Widget(),
                                    ),
                                    Positioned(
                                      left: 76.0,
                                      top: 935.0,
                                      right: null,
                                      bottom: null,
                                      width: 209.0,
                                      height: 42.0,
                                      child: GeneratedGroup9Widget(),
                                    ),
                                    Positioned(
                                      left: 121.0,
                                      top: 767.0,
                                      right: null,
                                      bottom: null,
                                      width: 137.0,
                                      height: 19.0,
                                      child:
                                          GeneratedCourseRegistrationWidget(),
                                    ),
                                    Positioned(
                                      left: 99.0,
                                      top: 770.0,
                                      right: null,
                                      bottom: null,
                                      width: 11.0,
                                      height: 11.0,
                                      child: GeneratedRectangle10Widget(),
                                    ),
                                    Positioned(
                                      left: 66.0,
                                      top: 752.0,
                                      right: null,
                                      bottom: null,
                                      width: 230.0,
                                      height: 150.0,
                                      child: GeneratedRectangle12Widget(),
                                    ),
                                    Positioned(
                                      left: 85.0,
                                      top: 1042.0,
                                      right: null,
                                      bottom: null,
                                      width: 191.0,
                                      height: 86.0,
                                      child: GeneratedGroup6Widget(),
                                    ),
                                    Positioned(
                                      left: 65.0,
                                      top: 1010.0,
                                      right: null,
                                      bottom: null,
                                      width: 230.0,
                                      height: 150.0,
                                      child: GeneratedRectangle13Widget(),
                                    ),
                                    Positioned(
                                      left: 109.0,
                                      top: 849.0,
                                      right: null,
                                      bottom: null,
                                      width: 152.0,
                                      height: 38.0,
                                      child: GeneratedGroup35Widget(),
                                    ),
                                    Positioned(
                                      left: 109.0,
                                      top: 798.0,
                                      right: null,
                                      bottom: null,
                                      width: 152.0,
                                      height: 38.0,
                                      child: GeneratedGroup38Widget(),
                                    )
                                  ]),
                            ))
                      ])),
                );
              }),
            )
          : Center(
              child: CircularProgressIndicator(),
            ),
    );
  }
}
