import 'package:flutter/material.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedGroup23Widget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedEnterpasswordWidget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedDonthaveanaccountWidget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedGroup20Widget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedRectangle3Widget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedLogintoyouraccountWidget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedGroup22Widget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedRectangle1Widget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget/generated/GeneratedDownload11Widget.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Scaffold(
      body: SafeArea(
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              SizedBox(
                width: double.infinity,
              ),
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  width: 360.0,
                  height: 800.0,
                  child: Stack(
                      // clipBehavior: Clip.none,
                      // fit: StackFit.expand,
                      alignment: Alignment.center,
                      children: [
                        ClipRRect(
                          borderRadius: BorderRadius.zero,
                          child: Container(
                            color: Color.fromARGB(255, 255, 255, 255),
                          ),
                        ),
                        Positioned(
                          left: 0.0,
                          top: 195.0,
                          right: null,
                          bottom: null,
                          width: 360.0,
                          height: 605.0,
                          child: GeneratedRectangle1Widget(),
                        ),
                        Positioned(
                          left: 125.0,
                          top: 39.0,
                          right: null,
                          bottom: null,
                          width: 110.0,
                          height: 110.0,
                          child: GeneratedDownload11Widget(),
                        ),
                        Positioned(
                          left: 95.0,
                          top: 244.0,
                          right: null,
                          bottom: null,
                          width: 171.0,
                          height: 21.0,
                          //Login to your account text
                          child: GeneratedLogintoyouraccountWidget(),
                        ),
                        Positioned(
                          left: 96.0,
                          top: 648.0,
                          right: null,
                          bottom: null,
                          width: 183.0,
                          height: 21.0,
                          //don't have an account
                          child: GeneratedDonthaveanaccountWidget(),
                        ),

                        Form(
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            children: [
                              TextFormField(),
                              Positioned(
                                  left: 42.0,
                                  top: 510.0,
                                  right: null,
                                  bottom: null,
                                  width: 106.0,
                                  height: 19.0,
                                  child: TextFormField()),
                            ],
                          ),
                        ),
                        //password box
                        // Positioned(
                        //   left: 32.0,
                        //   top: 476.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 297.0,
                        //   height: 44.0,
                        //   child: GeneratedRectangle3Widget(),
                        // ),

                        // Passsword level
                        // Positioned(
                        //   left: 32.0,
                        //   top: 450.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 70.0,
                        //   height: 22.0,
                        //   child: GeneratedPasswordWidget(),
                        // ),

                        //Email Part
                        // Positioned(
                        //   left: 32.0,
                        //   top: 340.0,
                        //   right: null,
                        //   bottom: null,
                        //   width: 297.0,
                        //   height: 70.0,
                        //   child: GeneratedGroup20Widget(),
                        // ),
                        //

                        //enter password Label
                        Positioned(
                          left: 42.0,
                          top: 489.0,
                          right: null,
                          bottom: null,
                          width: 106.0,
                          height: 19.0,
                          child: GeneratedEnterpasswordWidget(),
                        ),
                        Positioned(
                          left: 75.0,
                          top: 566.0,
                          right: null,
                          bottom: null,
                          width: 209.0,
                          height: 42.0,
                          child: GeneratedGroup22Widget(),
                        ),
                        Positioned(
                          left: 75.0,
                          top: 690.0,
                          right: null,
                          bottom: null,
                          width: 209.0,
                          height: 42.0,
                          child: GeneratedGroup23Widget(),
                        )
                      ]),
                ),
              ),
            ],
          ),
        ),
      ),
    ));
  }
}
