import 'package:flutter/material.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedEmailAddressWidget3.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedRectangle2Widget3.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedGroup26Widget.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedCreateanewaccountWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedRectangle3Widget3.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedMonicaGellerWidget.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedGroup28Widget.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/Generated122112ruetstudentacbdWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedRectangle1Widget3.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedAlreadyhaveanaccountWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedDownload11Widget3.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedNameWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget1/generated/GeneratedPasswordWidget3.dart';

/* Frame Sign up Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupPageWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 605.0,
                child: GeneratedRectangle1Widget3(),
              ),
              Positioned(
                left: 125.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 110.0,
                child: GeneratedDownload11Widget3(),
              ),
              Positioned(
                left: 31.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 44.0,
                child: GeneratedRectangle2Widget3(),
              ),
              Positioned(
                left: 31.0,
                top: 321.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 44.0,
                child: GeneratedRectangle6Widget1(),
              ),
              Positioned(
                left: 31.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 44.0,
                child: GeneratedRectangle3Widget3(),
              ),
              Positioned(
                left: 31.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 19.0,
                child: GeneratedEmailAddressWidget3(),
              ),
              Positioned(
                left: 31.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 22.0,
                child: GeneratedNameWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: GeneratedPasswordWidget3(),
              ),
              Positioned(
                left: 41.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 22.0,
                child: Generated122112ruetstudentacbdWidget1(),
              ),
              Positioned(
                left: 41.0,
                top: 334.0,
                right: null,
                bottom: null,
                width: 93.0,
                height: 19.0,
                child: GeneratedMonicaGellerWidget(),
              ),
              Positioned(
                left: 41.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 22.0,
                child: GeneratedWidget1(),
              ),
              Positioned(
                left: 96.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 21.0,
                child: GeneratedCreateanewaccountWidget1(),
              ),
              Positioned(
                left: 81.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 21.0,
                child: GeneratedAlreadyhaveanaccountWidget1(),
              ),
              Positioned(
                left: 76.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 42.0,
                child: GeneratedGroup28Widget(),
              ),
              Positioned(
                left: 76.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 42.0,
                child: GeneratedGroup26Widget(),
              )
            ]),
      ),
    ));
  }
}
