import 'package:flutter/material.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedGroup6Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedGroup9Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedGeneralInformationWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedCourseRegistrationWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedGroup3Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedGroup5Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedOngoingSemesterWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedDownload11Widget5.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedRectangle1Widget5.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedRectangle10Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedGroup10Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedGroup38Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedhomepage2widget/generated/GeneratedGroup35Widget1.dart';

/* Frame Home page 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHomepage2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 1250.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 360.0,
                      height: 1250.0,
                      child: Stack(
                          clipBehavior: Clip.none,
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 195.0,
                              right: null,
                              bottom: null,
                              width: 360.0,
                              height: 1055.0,
                              child: GeneratedRectangle1Widget5(),
                            ),
                            Positioned(
                              left: 125.0,
                              top: 39.0,
                              right: null,
                              bottom: null,
                              width: 110.0,
                              height: 110.0,
                              child: GeneratedDownload11Widget5(),
                            ),
                            Positioned(
                              left: 34.0,
                              top: 302.0,
                              right: null,
                              bottom: null,
                              width: 292.0,
                              height: 197.0,
                              child: GeneratedGroup10Widget1(),
                            ),
                            Positioned(
                              left: 103.0,
                              top: 244.0,
                              right: null,
                              bottom: null,
                              width: 156.0,
                              height: 21.0,
                              child: GeneratedGeneralInformationWidget1(),
                            ),
                            Positioned(
                              left: 108.0,
                              top: 626.0,
                              right: null,
                              bottom: null,
                              width: 147.0,
                              height: 21.0,
                              child: GeneratedOngoingSemesterWidget1(),
                            ),
                            Positioned(
                              left: 54.0,
                              top: 552.0,
                              right: null,
                              bottom: null,
                              width: 252.0,
                              height: 42.0,
                              child: GeneratedGroup3Widget1(),
                            ),
                            Positioned(
                              left: 76.0,
                              top: 677.0,
                              right: null,
                              bottom: null,
                              width: 209.0,
                              height: 42.0,
                              child: GeneratedGroup5Widget1(),
                            ),
                            Positioned(
                              left: 76.0,
                              top: 935.0,
                              right: null,
                              bottom: null,
                              width: 209.0,
                              height: 42.0,
                              child: GeneratedGroup9Widget1(),
                            ),
                            Positioned(
                              left: 121.0,
                              top: 767.0,
                              right: null,
                              bottom: null,
                              width: 137.0,
                              height: 19.0,
                              child: GeneratedCourseRegistrationWidget1(),
                            ),
                            Positioned(
                              left: 99.0,
                              top: 770.0,
                              right: null,
                              bottom: null,
                              width: 11.0,
                              height: 11.0,
                              child: GeneratedRectangle10Widget1(),
                            ),
                            Positioned(
                              left: 66.0,
                              top: 752.0,
                              right: null,
                              bottom: null,
                              width: 230.0,
                              height: 150.0,
                              child: GeneratedRectangle12Widget1(),
                            ),
                            Positioned(
                              left: 85.0,
                              top: 1042.0,
                              right: null,
                              bottom: null,
                              width: 191.0,
                              height: 86.0,
                              child: GeneratedGroup6Widget1(),
                            ),
                            Positioned(
                              left: 65.0,
                              top: 1010.0,
                              right: null,
                              bottom: null,
                              width: 230.0,
                              height: 150.0,
                              child: GeneratedRectangle13Widget1(),
                            ),
                            Positioned(
                              left: 109.0,
                              top: 849.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 38.0,
                              child: GeneratedGroup35Widget1(),
                            ),
                            Positioned(
                              left: 109.0,
                              top: 798.0,
                              right: null,
                              bottom: null,
                              width: 152.0,
                              height: 38.0,
                              child: GeneratedGroup38Widget1(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
