import 'package:flutter/material.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedRectangle1Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedRectangle2Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedWidget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedRectangle3Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/Generated122112ruetstudentacbdWidget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedDonthaveanaccountWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedGroup21Widget.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedEmailAddressWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedLogintoyouraccountWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedDownload11Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedloginpagewidget1/generated/GeneratedGroup24Widget.dart';

/* Frame Login Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedLoginPageWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 605.0,
                child: GeneratedRectangle1Widget1(),
              ),
              Positioned(
                left: 125.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 110.0,
                child: GeneratedDownload11Widget1(),
              ),
              Positioned(
                left: 95.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 21.0,
                child: GeneratedLogintoyouraccountWidget1(),
              ),
              Positioned(
                left: 96.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 183.0,
                height: 21.0,
                child: GeneratedDonthaveanaccountWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 366.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 44.0,
                child: GeneratedRectangle2Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 476.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 44.0,
                child: GeneratedRectangle3Widget1(),
              ),
              Positioned(
                left: 32.0,
                top: 340.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 19.0,
                child: GeneratedEmailAddressWidget1(),
              ),
              Positioned(
                left: 32.0,
                top: 450.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: GeneratedPasswordWidget1(),
              ),
              Positioned(
                left: 42.0,
                top: 379.0,
                right: null,
                bottom: null,
                width: 185.0,
                height: 22.0,
                child: Generated122112ruetstudentacbdWidget(),
              ),
              Positioned(
                left: 42.0,
                top: 489.0,
                right: null,
                bottom: null,
                width: 61.0,
                height: 22.0,
                child: GeneratedWidget(),
              ),
              Positioned(
                left: 75.0,
                top: 566.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 42.0,
                child: GeneratedGroup21Widget(),
              ),
              Positioned(
                left: 75.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 42.0,
                child: GeneratedGroup24Widget(),
              )
            ]),
      ),
    ));
  }
}
