import 'package:flutter/material.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/Generated1Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/GeneratedRectangle8Widget3.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/GeneratedGroup1Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/Generated1Widget.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/GeneratedRectangle9Widget3.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/Generated7Widget.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/GeneratedRectangle6Widget5.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/GeneratedWehavesentyouaverificationcodethroughemailPleaseenterth1.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/GeneratedEllipse1Widget1.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/GeneratedGroup29Widget.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/Generated0Widget.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget1/generated/GeneratedRectangle7Widget3.dart';

/* Frame Verification Code
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerificationCodeWidget1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 276.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 36.0,
                child:
                    GeneratedWehavesentyouaverificationcodethroughemailPleaseenterth1(),
              ),
              Positioned(
                left: 81.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 22.0,
                child: Generated1Widget(),
              ),
              Positioned(
                left: 213.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 22.0,
                child: Generated1Widget1(),
              ),
              Positioned(
                left: 147.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 22.0,
                child: Generated0Widget(),
              ),
              Positioned(
                left: 279.0,
                top: 127.0,
                right: null,
                bottom: null,
                width: 16.0,
                height: 22.0,
                child: Generated7Widget(),
              ),
              Positioned(
                left: 64.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedRectangle6Widget5(),
              ),
              Positioned(
                left: 196.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedRectangle8Widget3(),
              ),
              Positioned(
                left: 130.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedRectangle7Widget3(),
              ),
              Positioned(
                left: 262.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedRectangle9Widget3(),
              ),
              Positioned(
                left: 75.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 42.0,
                child: GeneratedGroup29Widget(),
              ),
              Positioned(
                left: 315.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedEllipse1Widget1(),
              ),
              Positioned(
                left: 326.5862121582031,
                top: 22.586181640625,
                right: null,
                bottom: null,
                width: 8.567963600158691,
                height: 8.82758617401123,
                child: GeneratedGroup1Widget1(),
              )
            ]),
      ),
    ));
  }
}
