import 'package:flutter/material.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget/generated/GeneratedRectangle7Widget2.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget/generated/GeneratedWehavesentyouaverificationcodethroughemailPleaseenterth.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget/generated/GeneratedEllipse1Widget.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget/generated/GeneratedVerifyWidget.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget/generated/GeneratedRectangle6Widget4.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget/generated/GeneratedRectangle9Widget2.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget/generated/GeneratedRectangle4Widget7.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget/generated/GeneratedGroup1Widget.dart';
import 'package:flutterapp/cse_202100app/generatedverificationcodewidget/generated/GeneratedRectangle8Widget2.dart';

/* Frame Verification Code
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedVerificationCodeWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 276.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 22.0,
                top: 52.0,
                right: null,
                bottom: null,
                width: 318.0,
                height: 36.0,
                child:
                    GeneratedWehavesentyouaverificationcodethroughemailPleaseenterth(),
              ),
              Positioned(
                left: 64.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedRectangle6Widget4(),
              ),
              Positioned(
                left: 196.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedRectangle8Widget2(),
              ),
              Positioned(
                left: 130.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedRectangle7Widget2(),
              ),
              Positioned(
                left: 262.0,
                top: 114.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 44.0,
                child: GeneratedRectangle9Widget2(),
              ),
              Positioned(
                left: 75.0,
                top: 192.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 42.0,
                child: GeneratedRectangle4Widget7(),
              ),
              Positioned(
                left: 160.0,
                top: 204.0,
                right: null,
                bottom: null,
                width: 44.0,
                height: 22.0,
                child: GeneratedVerifyWidget(),
              ),
              Positioned(
                left: 315.0,
                top: 11.0,
                right: null,
                bottom: null,
                width: 32.0,
                height: 32.0,
                child: GeneratedEllipse1Widget(),
              ),
              Positioned(
                left: 326.5862121582031,
                top: 22.586181640625,
                right: null,
                bottom: null,
                width: 8.567963600158691,
                height: 8.82758617401123,
                child: GeneratedGroup1Widget(),
              )
            ]),
      ),
    ));
  }
}
