import 'package:flutter/material.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedPasswordWidget2.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedEmailAddressWidget2.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedEnterpasswordWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedRectangle4Widget2.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedAlreadyhaveanaccountWidget.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedCreateanewaccountWidget.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedContinueWidget.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedEnteryouremailaddressWidget1.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedRectangle1Widget2.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedRectangle3Widget2.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedRectangle2Widget2.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedDownload11Widget2.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedGroup27Widget.dart';
import 'package:flutterapp/cse_202100app/generatedsignuppagewidget/generated/GeneratedGroup25Widget.dart';

/* Frame Sign up Page
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedSignupPageWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 360.0,
        height: 800.0,
        child: Stack(
            clipBehavior: Clip.none,
            fit: StackFit.expand,
            alignment: Alignment.center,
            children: [
              ClipRRect(
                borderRadius: BorderRadius.zero,
                child: Container(
                  color: Color.fromARGB(255, 255, 255, 255),
                ),
              ),
              Positioned(
                left: 0.0,
                top: 195.0,
                right: null,
                bottom: null,
                width: 360.0,
                height: 605.0,
                child: GeneratedRectangle1Widget2(),
              ),
              Positioned(
                left: 125.0,
                top: 39.0,
                right: null,
                bottom: null,
                width: 110.0,
                height: 110.0,
                child: GeneratedDownload11Widget2(),
              ),
              Positioned(
                left: 31.0,
                top: 414.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 44.0,
                child: GeneratedRectangle2Widget2(),
              ),
              Positioned(
                left: 31.0,
                top: 512.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 44.0,
                child: GeneratedRectangle3Widget2(),
              ),
              Positioned(
                left: 31.0,
                top: 388.0,
                right: null,
                bottom: null,
                width: 96.0,
                height: 19.0,
                child: GeneratedEmailAddressWidget2(),
              ),
              Positioned(
                left: 31.0,
                top: 486.0,
                right: null,
                bottom: null,
                width: 70.0,
                height: 22.0,
                child: GeneratedPasswordWidget2(),
              ),
              Positioned(
                left: 41.0,
                top: 427.0,
                right: null,
                bottom: null,
                width: 166.0,
                height: 19.0,
                child: GeneratedEnteryouremailaddressWidget1(),
              ),
              Positioned(
                left: 31.0,
                top: 295.0,
                right: null,
                bottom: null,
                width: 297.0,
                height: 70.0,
                child: GeneratedGroup27Widget(),
              ),
              Positioned(
                left: 41.0,
                top: 525.0,
                right: null,
                bottom: null,
                width: 106.0,
                height: 19.0,
                child: GeneratedEnterpasswordWidget1(),
              ),
              Positioned(
                left: 96.0,
                top: 244.0,
                right: null,
                bottom: null,
                width: 171.0,
                height: 21.0,
                child: GeneratedCreateanewaccountWidget(),
              ),
              Positioned(
                left: 81.0,
                top: 648.0,
                right: null,
                bottom: null,
                width: 202.0,
                height: 21.0,
                child: GeneratedAlreadyhaveanaccountWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 581.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 42.0,
                child: GeneratedRectangle4Widget2(),
              ),
              Positioned(
                left: 151.0,
                top: 593.0,
                right: null,
                bottom: null,
                width: 65.0,
                height: 22.0,
                child: GeneratedContinueWidget(),
              ),
              Positioned(
                left: 76.0,
                top: 690.0,
                right: null,
                bottom: null,
                width: 209.0,
                height: 42.0,
                child: GeneratedGroup25Widget(),
              )
            ]),
      ),
    ));
  }
}
